added workaround for more robust ffmpeg to mkv when frames dropped and added workaround for comskip segmentation fault (core dump) error

diff --git a/config/comskip/comchap b/config/comskip/comchap
--- a/config/comskip/comchap
+++ b/config/comskip/comchap
@@ -23,12 +23,12 @@ fi
 
 comskipini=$HOME/.comskip.ini
 
-deleteedl=false
-deletemeta=false
+deleteedl=true
+deletemeta=true
 deletelog=true
-deletelogo=true
+deletelogo=false
 deletetxt=true
-verbose=false
+verbose=true
 lockfile=""
 workdir=""
 
@@ -150,7 +150,12 @@ txtfile="$workdir${infile%.*}.txt"
 fi
 
 if [ ! -f "$edlfile" ]; then
-  $comskipPath -d 255 --ini="$comskipini" "$infile"
+  $comskipPath --ini="$comskipini" "$infile"
+
+  if [ ! -f "$edlfile" ] ; then
+    echo "Error running comskip. Re-running comskip on file: $infile"  1>&3 2>&4 >&2
+    $comskipPath --ini="$comskipini" "$infile"
+  fi
 
   if [ ! -f "$edlfile" ] ; then
     echo "Error running comskip. EDL File not found: $infile"  1>&3 2>&4 >&2
@@ -200,7 +205,7 @@ if $hascommercials ; then
     tempfile=`mktemp --suffix=."$outextension" "$outdir"/XXXXXXXX`
 
     echo Writing file to temporary file: "$tempfile"
-    if $ffmpegPath -loglevel error -hide_banner -nostdin -i "$infile" -i "$metafile" -map 0 -map_metadata 1  -codec copy -y "$tempfile" 1>&3 2>&4; then
+    if $ffmpegPath -fflags +genpts+igndts -loglevel error -hide_banner -nostdin -i "$infile" -i "$metafile" -map 0 -map_metadata 1  -codec copy -y "$tempfile" 1>&3 2>&4; then
       mv -f "$tempfile" "$outfile"
       echo Saved to: "$outfile"
     else
@@ -208,7 +213,7 @@ if $hascommercials ; then
       exitcode=-1
     fi
   else
-    if $ffmpegPath -loglevel error -hide_banner -nostdin -i "$infile" -i "$metafile" -map 0 -map_metadata 1 -codec copy -y "$outfile" 1>&3 2>&4; then
+    if $ffmpegPath -fflags +genpts+igndts -loglevel error -hide_banner -nostdin -i "$infile" -i "$metafile" -map 0 -map_metadata 1 -codec copy -y "$outfile" 1>&3 2>&4; then
       echo Saved to: "$outfile"
     else
       echo Error running ffmpeg: "$infile" 1>&3 2>&4 >&2
